services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio:local
    container_name: portfolio
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true